# Generated by Django 2.0.6 on 2018-08-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('score', models.FloatField()),
            ],
            options={
                'verbose_name_plural': '学生',
                'db_table': 'student',
            },
        ),
    ]
